# Generated by Django 2.1.4 on 2018-12-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosM',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m/$d/')),
                ('costo_presupuestado', models.CharField(max_length=10)),
                ('costo_real', models.CharField(max_length=10)),
                ('tienda_compra', models.CharField(max_length=20)),
                ('notas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiendasM',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=30)),
            ],
        ),
    ]
