# Generated by Django 2.1.4 on 2018-12-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listacompra', '0002_auto_20181212_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosm',
            old_name='nombreP',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tiendasm',
            old_name='nombreT',
            new_name='nombre',
        ),
    ]
