# Generated by Django 2.1.4 on 2018-12-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacompra', '0003_auto_20181212_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendasm',
            name='image_tienda',
            field=models.ImageField(blank=True, null=True, upload_to='tienda/%Y/%m/$d/'),
        ),
    ]
